# docker-compose.yml
version: '3'
services:
  IFC-API-Local:
    image: ifc-api/latest
    build:
      context: ../krande-IfcOpenShell/src/blenderbim
      dockerfile: Dockerfile
    pull_policy: build
    environment:
      EDGEDB_CLIENT_TLS_SECURITY: insecure
      EDGEDB_DSN: edgedb://ifcdbadmin:secret@edgedb-local:5656/edgedb
    ports:
      - "8000:8000"
    env_file:
      - src/server/api/fastapi_azure/config/local/local.env