name: ifcdb-dev
channels:
  - ifcopenshell
  - conda-forge
  - krande/label/dev
dependencies:
  - ada-py
  - occt
  - python
  - pyparsing
  - pytest
  - toposort
  - httpx
  - fastapi
  - uvicorn
  - hpp-fcl
  - starlette
  - pip
  - pip:
      - edgedb
      - rdflib
      - fastapi-azure-auth
      - azure-storage-queue
      - azure-identity
      - pydantic[dotenv]
      - fake-bpy-module-3.2
      - anyio[trio]
      - python-multipart
      - frozendict
      - deepdiff
      - pandas
