name: ifcdb-dev
channels:
  - krande/label/dev
  - conda-forge
dependencies:
  - ifcopenshell
  - python==3.10.5
  - pyparsing
  - pytest
  - toposort
  - httpx
  - fastapi
  - uvicorn
  - starlette
  - pip
  - pip:
      - edgedb
      - rdflib
      - fastapi-azure-auth
      - pydantic[dotenv]