name: ifcdb
channels:
  - krande/label/dev
  - conda-forge
dependencies:
  - ifcopenshell
  - python==3.10
  - pyparsing
  - pydantic
  - pytest
  - toposort
  - pip
  - pip:
      - edgedb
      - rdflib