FILES = ["MyCube/MyCube.ifc", "cube-advanced-brep.ifc", "tessellated-item.ifc", "MyBeam_w_holes/MyBeamWithHoles.ifc"]
ADD_CLASSES = [
    "IfcTelecomAddress",
    "IfcMember",
    "IfcColumn",
    "IfcPerson",
    "IfcIndexedPolygonalFace",
]
DEMO_PROJECT_CLASSES = [
    "IfcColourRgb",
    "IfcSurfaceStyleShading",
    "IfcFurnitureType",
    "IfcGeometricCurveSet",
    "IfcCartesianPointList2D",
    "IfcPolygonalFaceSet",
    "IfcStyledItem",
    "IfcSurfaceStyle",
    "IfcDoorType",
    "IfcCShapeProfileDef",
    "IfcRectangleHollowProfileDef",
    "IfcColumnType",
    "IfcCircleHollowProfileDef",
    "IfcMaterialLayerSet",
    "IfcMaterialLayer",
    "IfcPileType",
    "IfcRampType",
    "IfcCoveringType",
    "IfcWallType",
    "IfcSlabType",
    "IfcWindowType",
]
