# docker-compose.yml
version: '3'
services:
  IFC-API:
    image: ifc-api/latest
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    volumes:
      - "./config/azure:/code/certs"
    environment:
      EDGEDB_TLS_CA_FILE: /code/certs/cert.pem
      EDGEDB_CLIENT_TLS_SECURITY: insecure
    ports:
      - "8000:8000"
    env_file:
      - config/azure/.env