version: "3"
services:
  edgedb:
    image: edgedb/edgedb:1.4
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
    volumes:
      - "./dbschema:/dbschema"
    ports:
      - "5656:5656"