version: "3"
services:
  edgedb:
    image: edgedb/edgedb:2.0
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
      EDGEDB_DOCKER_LOG_LEVEL: debug
    volumes:
      - "./dbschema:/dbschema"
    ports:
      - "5656:5656"