version: "3"
services:
  edgedb:
    image: edgedb/edgedb:nightly
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
      EDGEDB_DOCKER_LOG_LEVEL: trace
    volumes:
      - "./dbschema:/dbschema"
    ports:
      - "5656:5656"