name: ifc-api
channels:
  - conda-forge
dependencies:
  - python==3.10.5
  - ifcopenshell
  - fastapi
  - uvicorn
  - starlette
  - toposort
  - pip
  - pip:
      - edgedb
      - fastapi-azure-auth
      - pydantic[dotenv]
      - python-multipart
      - frozendict
      - deepdiff
      - azure-storage-queue