# docker-compose.yml
version: '3'
services:
  ifc-designer-bot:
    build:
      context: ../../../
      dockerfile: ./src/client/IfcDesignerBot/service-ifc-designer-bot.Dockerfile
    environment:
      IFCDB_REST_API_URL: 'localhost:8000'
  ifc-db-api:
    image: ifc-api/latest
    build:
      context: ../../../
      dockerfile: service.api.Dockerfile
    volumes:
      - "./src/client/api/config/azure:/code/certs"
    environment:
      EDGEDB_TLS_CA_FILE: /code/certs/cert.pem
      EDGEDB_CLIENT_TLS_SECURITY: insecure
    ports:
      - "8000:8000"
    env_file:
      - ./.azure.env