on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: CI with EdgeDB action
    services:
      edgedb:
        image: edgedb/edgedb:1.4
        env:
          EDGEDB_SERVER_SECURITY: insecure_dev_mode
        ports:
          - 5656:5656
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: conda-incubator/setup-miniconda@v2  # https://github.com/conda-incubator/setup-miniconda
        with:
          activate-environment: ifcdb
          python-version: 3.10
          channel-priority: strict
          environment-file: environment.yml
          auto-update-conda: true

      - uses: edgedb/setup-edgedb@v1
        with:
          server-dsn: edgedb://localhost:5656
          instance-name: ci_edgedb_instance  # optional
      - run: edgedb query "SELECT 'Hello from GitHub Actions'"