name: ci-ifc-edgedb

on:
  push:
    paths:
      - src/**
      - tests/**

jobs:
  test:
    runs-on: ubuntu-latest
    name: CI with EdgeDB action
    services:
      edgedb:
        image: edgedb/edgedb:2.2
        env:
          EDGEDB_SERVER_SECURITY: insecure_dev_mode
          EDGEDB_USER: ifcdbadmin
          EDGEDB_PASSWORD: secret
        ports:
          - 5656:5656
    strategy:
      fail-fast: false
      matrix:
        pyver: [ { name: py310, distver: "3.10" } ]
        platform: [
          #          { name: Windows, distver: windows-latest, short: 'win-64' },
          { name: Linux, distver: ubuntu-latest, short: 'linux-64' },
          #          { name: macOS, distver: macos-latest, short: 'osx-64' }
        ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: conda-incubator/setup-miniconda@v2  # https://github.com/conda-incubator/setup-miniconda
        with:
          activate-environment: ifcdb
          python-version: ${{ matrix.pyver.distver }}
          channel-priority: strict
          environment-file: environment.dev.yml
          auto-update-conda: true
      - name: Install python package
        run: |
          python -m pip install --no-deps --ignore-installed .
        shell: bash -l {0}
      - uses: edgedb/setup-edgedb@v1
        with:
          cli-version: nightly
          server-version: none
      - name: EdgeDB test
        run: | 
          which edgedb
          edgedb info
      - name: Test package
        run: pytest tests
        shell: bash -l {0}
        env:
          EDGEDB_DSN: edgedb://ifcdbadmin:secret@localhost
          EDGEDB_CLIENT_TLS_SECURITY: insecure
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1
