name: ci-ifc-edgedb

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: CI with EdgeDB action
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: conda-incubator/setup-miniconda@v2  # https://github.com/conda-incubator/setup-miniconda
        with:
          activate-environment: ifcdb
          python-version: "3.10"
          channel-priority: strict
          environment-file: environment.yml
          auto-update-conda: true
      - name: Install python package
        run: |
          python -m pip install --no-deps --ignore-installed .
        shell: bash -l {0}
      - uses: edgedb/setup-edgedb@v1
      - name: EdgeDB test
        run: | 
          which edgedb
          edgedb info
      - name: Test package
        run: pytest tests
        shell: bash -l {0}
#        env:
#          EDGEDB_SERVER: "--tls-security=insecure -P 5656"
