name: ci-ifc-edgedb-schema

on:
  push:
    paths:
      - src/server/schema/**

env:
  WORKDIR: src/server/schema/partial_schemas/db/basic
  CON_PARAMS: --tls-security=insecure -P 5656
  SERVER_VERSION: 2.1

jobs:
  test:
    runs-on: ubuntu-latest
    name: EdgeDB schema - "${{ matrix.WORKDIR.name }}"
    services:
      edgedb:
        image: edgedb/edgedb:2.1
        env:
          EDGEDB_SERVER_SECURITY: insecure_dev_mode
          EDGEDB_SERVER_LOG_LEVEL: debug
        ports:
          - 5656:5656
    strategy:
      fail-fast: false
      matrix:
        WORKDIR: [
          { name: basic, dir: "src/server/schema/partial_schemas/db/basic" },
          { name: complete, dir: "src/server/schema/complete_schema" }
        ]
    env:
      EDGEDB_DATABASE: "${{ matrix.WORKDIR.name }}"
    steps:
      - uses: actions/checkout@v2
      - uses: edgedb/setup-edgedb@v1
      - name: EdgeDB Clear previous migration and Create a new database
        run: |
          rm -rf ./dbschema/migrations
          edgedb $CON_PARAMS database create ${{ matrix.WORKDIR.name }}
        working-directory: ${{ matrix.WORKDIR.dir }}
      - name: EdgeDB Migrate create
        run: |
            edgedb $CON_PARAMS migration create --non-interactive
        working-directory: ${{ matrix.WORKDIR.dir }}
      - name: EdgeDB Apply Migration
        run: |
          edgedb $CON_PARAMS migration apply
        working-directory: ${{ matrix.WORKDIR.dir }}
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1
      - name: Make zip file from the final migrations and schema
        run: |
          zip -r ${{ matrix.WORKDIR.name }}.zip ${{ matrix.WORKDIR.dir }}
      - name: Upload Zip file to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.WORKDIR.name }}.zip
          asset_name: IFC-schema-${{ matrix.WORKDIR.name }}.zip
          tag: "IFC-schema-${{ matrix.WORKDIR.name }}"
          overwrite: true
          body: "IFC-schema-${{ matrix.WORKDIR.name }}"