name: ci-ifc-edgedb-schema

on: push

env:
  WORKDIR: src/server/schema/partial_schemas/db/basic
  CON_PARAMS: --tls-security=insecure -P 5656

jobs:
  test:
    runs-on: ubuntu-latest
    name: EdgeDB schema - "${{ matrix.WORKDIR.name }}"
    services:
      edgedb:
        image: edgedb/edgedb:2.1
        env:
          EDGEDB_SERVER_SECURITY: insecure_dev_mode
          EDGEDB_SERVER_LOG_LEVEL: debug
        ports:
          - 5656:5656
    strategy:
      fail-fast: false
      matrix:
        WORKDIR: [
          { name: basic, dir: "src/server/schema/partial_schemas/db/basic" },
          { name: complete, dir: "src/server/schema/complete_schema" }
        ]
    steps:
      - uses: actions/checkout@v2
      - uses: edgedb/setup-edgedb@v1
      - name: EdgeDB Migrate create
        run: |
            rm -rf ./dbschema/migrations
            edgedb database create ${{ matrix.WORKDIR.name }}
            edgedb -d ${{ matrix.WORKDIR.name }} $CON_PARAMS migration create --non-interactive
        working-directory: ${{ matrix.WORKDIR.dir }}
      - name: EdgeDB Apply Migration
        run: |
          edgedb -d ${{ matrix.WORKDIR.name }} $CON_PARAMS migration apply
        working-directory: ${{ matrix.WORKDIR.dir }}
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1