name: ci-ifc-schema

on:
  push:
    paths:
      - src/**
      - .github/workflows/ci.yml

jobs:
  test:
    name: ${{ matrix.platform.name }}-${{ matrix.pyver.name }}
    runs-on: ${{ matrix.platform.distver }}
    defaults:
      run:
        shell: bash -l {0}
    env:
      CONDAENV: base
    strategy:
      fail-fast: false
      matrix:
        pyver: [ { name: py310, distver: '3.10.2'}]
        platform: [
          { name: Windows, distver: windows-latest, short: 'win-64' },
          { name: Linux, distver: ubuntu-latest, short: 'linux-64' },
          { name: macOS, distver: macos-latest, short: 'osx-64' }
        ]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2  # https://github.com/conda-incubator/setup-miniconda
        with:
          activate-environment: ${{ env.CONDAENV }}
          python-version: ${{ matrix.pyver.distver }}
          channel-priority: strict
          environment-file: environment.yml
          auto-update-conda: true
      - name: Build and Test package
        run: |
          python -m pip install --no-deps --ignore-installed .
          cd tests && pytest .

