version: "3"
services:
  edgedb:
    image: edgedb/edgedb
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
      EDGEDB_DOCKER_LOG_LEVEL: debug
      EDGEDB_SERVER_EXTRA_ARGS: --admin-ui=enabled
      EDGEDB_SERVER_USER: ifcdbadmin
      EDGEDB_SERVER_PASSWORD: secret
    volumes:
      - "./dbschema:/dbschema"
    ports:
      - "5656:5656"